### ISSUE TITLE
all the entities are view only

### ISSUE THREAD

**Issue by nikogusm** [oyvindwe/connectlife-ha#1]
hello, i have installed your addon and it worked fine. Thank you for your job. But i have installed my Hisense Air conditioners and all the entities that i recieve are view only, all sensors to get the state of the AC but nothing to control it. Is it possible to improve it?

Thank you

**Comment by oyvindwe** [comment]
Hi @nikogusm - thank you for you feedback!

I'm currently investigating legal values for all the sensors. The next step is indeed to try to send commands to the API, but as I only have a dishwasher I have very limited testing possibilities.

It would be nice to make a [climate entity](https://developers.home-assistant.io/docs/core/entity/climate) of the air conditioner - are you able to share a JSON dump of the attributes for you appliance?

**Comment by nikogusm** [comment]
i tried to do an export but i don't know how to do it. can you help me?

**Comment by oyvindwe** [comment]
> i tried to do an export but i don't know how to do it. can you help me?

With Python 3.11 or newer:
```
pip install connectlife
python -m connectlife.dump my_connectlife_username my_connectlife_password
```

Replace `my_connectlife_username` and `my_connectlife_password` of course.

This should produce a JSON dump with private information redacted (`deviceId`, `puid`, and ``wifiId`)

**Comment by Monacoslo** [comment]
> i tried to do an export but i don't know how to do it. can you help me?

If you are not familiar with the phyton, you can also installl https://github.com/bilan/connectlife-api-connector and just copy the content of the log produced by addon and share it.

Which appliance do you have?

**Comment by macieq56** [comment]
Hello, I have a dump for Hisense/Gorenje Split Pandora AST-18UW4RXATE00A air conditioner (attached)
[airCondDumpHisense.json](https://github.com/oyvindwe/connectlife-ha/files/15353863/airCondDumpHisense.json)

**Comment by oyvindwe** [comment]
I have started porting support for air conditioner from https://github.com/bilan/connectlife-api-connector, but since I don't own one myself I'll not be able to test it properly. I can push the development branch when it's a bit more polished if someone wants to contribute coding and/or testing it.

**Comment by nikogusm** [comment]
hello @oyvindwe sorry for the late reply. i can test it out, when you push i'm going to update your plugin from HACS store.

**Comment by oyvindwe** [comment]
I have just pushed the branch [climate](https://github.com/oyvindwe/connectlife-ha/tree/climate), but it's only a starting point, and not ready to go even to HACS. Feel free to fork the repository and contribute PRs!

**Comment by trajano** [comment]
@psylenced I have a [dehumidifier](https://github.com/oyvindwe/connectlife-ha/issues/6) in my case I have a `t_work_mode` value like yours does your mapping and my mapping match?

       // 1 == manual (which allows setting of target) 
        // 0 == continuous 
        // 2 == auto which basically sets humidity to 50 and auto

**Comment by oyvindwe** [comment]
I must admin I'm really struggling with setting properties. I'm trying to do the same as in https://github.com/bilan/connectlife-api-connector/blob/main/app/Services/ConnectlifeApiService.php#L30-L44

However, all I get back is
```
{
    "message": "Server Error"
}
```

**Comment by trajano** [comment]
@oyvindwe do you have your branch with the code to do the update so I can take a look at it maybe it's something odd with the HTTP client implementation

**Comment by trajano** [comment]
I tried to do it via curl but I am getting blocked by cloudflare
```
curl -v -H 'Content-type: application/json' -H 'X-Token: <token>' -XPOST --data '
{
"puid": "<redacted>",
"properties": { 
}
}' https://connectlife.bapi.ovh/appliances
```

**Comment by oyvindwe** [comment]
> do you have your branch with the code to do the update

- `connectlife` library: https://github.com/oyvindwe/connectlife/tree/write-properties
- HA integration (includes entity service): https://github.com/oyvindwe/connectlife-ha/tree/set-value-service

Note that most properties are probably read-only. I have tried to set the property value as both string and integer without success. I'm mostly experiencing using `curl`.

> I tried to do it via curl but I am getting blocked by cloudflare

As you discovered in https://github.com/oyvindwe/connectlife-ha/issues/6#issuecomment-2207510322 `User-Agent` seems to be a required header.

**Comment by oyvindwe** [comment]
I found my bug! I was passing `deviceId` as `puid` 🤦 

I will make a release shortly.

**Comment by trajano** [comment]
Great @oyvindwe  hopefully we see the update on HACS soon.  So far I only see 0.1.0 or 0.0.6

**Comment by CyberrNerd** [comment]
Hoe can I set values? I only see sensors for my dishwasher? Great job!

**Comment by oyvindwe** [comment]
@CyberrNerd I just updated [README.md] with instructions.

**Comment by CyberrNerd** [comment]
Ah great thanks, do you perhaps know which value to remote start the dishwasher? Or better, how can I see which values are available?

**Comment by oyvindwe** [comment]
> Ah great thanks, do you perhaps know which value to remote start the dishwasher? Or better, how can I see which values are available?

These are the great questions! As there is no data dictionaries published, we will need to figure out the properties and values to use ourselves.

For AC devices, the `t_*` properties seems writeable. E.g. set `t_power` to 0 to turn off and to 1 to turn it on.

I only have a dishwasher myself. I have not yet figured out how to remote control it, but you will first have to set it to remote start on the actual appliance.
