### ISSUE TITLE
Devices become unavailable every 1 hour

### ISSUE THREAD

**Issue by marcominiluca** [oyvindwe/connectlife-ha#101]
It happens several times.. looking at the logbook I see they become unavailable every 1 hour.

![image](https://github.com/user-attachments/assets/2605490f-f959-4edf-ac2f-ea9c667d8f18)

**Comment by oyvindwe** [comment]
Any information from the log? Could this be relates to issue #86 ?

**Comment by marcominiluca** [comment]
Yes, seems like the same problem. I’ll enable the log for few hours and
I’ll let you know

Il giorno gio 8 ago 2024 alle 19:58 Øyvind Matheson Wergeland <
***@***.***> ha scritto:

**Comment by marcominiluca** [comment]
Enable log for 2 hours..

![image](https://github.com/user-attachments/assets/0ea5a9aa-5250-4992-9a1a-35639c2c8719)

**Comment by oyvindwe** [comment]
I also get these 500 errors with irregular intervals. I think it's correct behaviour to go to unavailable when that occurs, but it's sad that the ConnectLife API is so unstable.

**Comment by oyvindwe** [comment]
Should be fixed in [version 0.16.0](https://github.com/oyvindwe/connectlife-ha/releases/tag/v0.16.0).
