### ISSUE TITLE
Cannot disable beep to control in the night without noise

### ISSUE THREAD

**Issue by jguerre** [oyvindwe/connectlife-ha#102]
Cannot disable beep to control in the night without noise.

Thanks a lot!

**Comment by oyvindwe** [comment]
This can be set in Integrations -> ConnectLife -> Configure -> Configure a device

Needs to be documented.

**Comment by jguerre** [comment]
Thanks a lot! You have develop a wonderful add-on that adds so much value to my Air Conditioned (6 units). Infinite thanks!
