### ISSUE TITLE
Refactoring may be in order for strings.json and en.json. 

### ISSUE THREAD

**Issue by psycho202** [oyvindwe/connectlife-ha#111]
Refactoring may be in order for strings.json and en.json. 
Fan modes "Middle_low" and "middle_high" are split off from the rest of the fan speeds. 
They're at lines 232 and 233 under fan_mode, whereas the rest of the fan modes are at lines 659 to 661 under t_fan_speed state

I took a look at specifically those fan modes, as I didn't find them at first glance. Possibly other values for different device types may also be split up like this.

**Comment by oyvindwe** [comment]
`middle_low` and `middle_high` are extensions to the [Climate entity fan modes](https://github.com/home-assistant/core/blob/dev/homeassistant/components/climate/strings.json#L48-L61), which supports several modes OOTB.

`f_fan_speed` at line 659 is a select entity used by other types of devices (dehumidifier, water heater) that don't have fan mode OOTB.
