### ISSUE TITLE
Problem with 009-104 with Aeh W4G2 module

### ISSUE THREAD

**Issue by maverik80** [oyvindwe/connectlife-ha#115]
Hi guys, has anyone by chance encountered problems with hardware 009-104 and Aeh W4Gx wifi module? I control the temperature from off, the ignition does not work. However it finds all three of my Split.

**Comment by oyvindwe** [comment]
You may reach a wider audience if you ask on a ConnectLife forum on the [Home Assistant Commity](https://community.home-assistant.io/) site.

**Comment by oyvindwe** [comment]
Closing as this integration cannot fix this issue.
