### ISSUE TITLE
Device 009-128 - Switching from mode OFF to COOL changes set temperature

### ISSUE THREAD

**Issue by psycho202** [oyvindwe/connectlife-ha#117]
When changing the mode of my AC of model 009-128 from off to cool, the AC starts up and sets to cool to 26°C, regardless of what the temperature is set to in the climate entity. 

When switching work mode, it seems that it takes all other settings from the last time the unit was on, ie display off, fan speed, ...
Only the temperature seems to reset to this (to me) arbitrary value of 26°C

I updated to v0.17 to make sure that my own testing around the config files did not cause this issue. 

Any way for me to trace or verify what may be happening so I can assist with troubleshooting this issue? 
My workaround now is to add a preset which includes the temps, but this is not a long-term fix as it will get overwritten when updating the integration.

**Comment by oyvindwe** [comment]
If you enable debug logging for the integration you should see the messages sent to the ConnectLife API.

I suspect HA only sends a mode change, and the device has a default target temperature. It will probably not hurt any other AC units if target temperature is always sent when changing mode (except to off). I can look into this.

**Comment by oyvindwe** [comment]
@psycho202 Are you able to test the change in PR #118 and see if it fixes your problem?

I don't have any AC unit myself, so I can't test if it works or have unintended side effects.

**Comment by psycho202** [comment]
> @psycho202 Are you able to test the change in PR #118 and see if it fixes your problem?
> 
> I don't have any AC unit myself, so I can't test if it works or have unintended side effects.

Tested, problem is indeed fixed. Upon receiving the mode switch command from the cloud, the AC unit receives the correct temperature setting now. 

No unintended side effects noticed at this point. No debug log entries found showing errors or issues.

**Comment by oyvindwe** [comment]
Thank you for verifying!
