### ISSUE TITLE
Climate support

### ISSUE THREAD

**Issue by trajano** [oyvindwe/connectlife-ha#12]
Ideally we should use the `Climate` API but obviously this would be device specific.  The way I was thinking was that if I use Climate to set the desired humidity to 45% then the following should occur

If present humidity is above 45% then
* turn dehumidifier on
* set it to "continuous mode" (rather than setting the desired humidity on the device)
* set the fan to high (or low depending on some other setting)

I did the above as an automation myself, but it would be nice if it had a nicer API. 

This should be an extension to #1 and #6 primarily.  But perhaps the data dictionary should accommodate for it.

**Comment by oyvindwe** [comment]
My original idea was to create a climate entity based on device type, and for those devices not create sensor entities for the properties that are used in the climate entity. However, I realised that we needed the data dictionaries first, and maybe add something to the data dictionary to control creating climate entities.

In the meanwhile, you could also try to map sensor entities using [Template Climate](https://github.com/jcwillox/hass-template-climate).

Also, feel free to submit PRs with data dictionaries and/or code!

**Comment by Monacoslo** [comment]
I created some template sensors for my oven, washing machine and dryer and combine them to the card with most useful sensors. Would it make sense to share them somehow here?

**Comment by oyvindwe** [comment]
[Version 0.3.0](https://github.com/oyvindwe/connectlife-ha/releases/tag/v0.3.0) with support for climate devices has just been released.

Note that it lacks some feature that I plan to add over the next few weeks:
- Preset modes (e.g. eco)
- Setting HVAC mode except to off/auto
- Min/max temperatures

**Comment by oyvindwe** [comment]
More releases today:
* [Version 0.4.0](https://github.com/oyvindwe/connectlife-ha/releases/tag/v0.4.0) adds support for `current_humidity` and `target_humidity`
* [Version 0.4.1](https://github.com/oyvindwe/connectlife-ha/releases/tag/v0.4.1) fixes an issue with the climate entity name

**Comment by oyvindwe** [comment]
[Version 0.10.0](https://github.com/oyvindwe/connectlife-ha/releases/tag/v0.10.0) adds support for presets.

Now only `target_temperature_max` and `target_temperature_min` is missing. I have not yet seen a ConnectLife device that supports this, so closing this issue as completed for now. This is also documented in [README.md](https://github.com/oyvindwe/connectlife-ha?tab=readme-ov-file#climate-entities)
