### ISSUE TITLE
Mapped properties are still hidden

### ISSUE THREAD

**Issue by gregrs-uk** [oyvindwe/connectlife-ha#121]
From the [data dictionaries readme](https://github.com/oyvindwe/connectlife-ha/tree/main/custom_components/connectlife/data_dictionaries#create-your-own-mapping-file) I was expecting properties that I've mapped as part of https://github.com/oyvindwe/connectlife-ha/pull/120 to be shown, but they are still marked as hidden and not shown on the default Overview dashboard.

The attached screenshots show the device page (accessed from Settings > Integrations > ConnectLife > 1 device) and the default Overview dashboard. The `sensor`s are hidden. The `select`s are shown on the dashboard and on the Controls section of the device page, and can be controlled successfully, but strangely say 'Hidden' and 'Unavailable' in the Sensors section of the device page.

My Home Assistant versions are: Core 2024.8.0 and Frontend 20240806.1.

![device page 1](https://github.com/user-attachments/assets/d1889047-2d40-4127-a48d-7e724d621f94)
![device page 2](https://github.com/user-attachments/assets/b9ddb5c6-d8f4-469a-af9b-3cd146064b78)
![overview dashboard](https://github.com/user-attachments/assets/64cddaf5-e359-46d7-a8fa-8d354a45442c)

**Comment by oyvindwe** [comment]
The disabled sensor properties are unfortunately out of the control of the integration. This happens during mapping properties when you change the entity type from the default (sensor) to something else (e.g. select). You have to delete these entities manually: https://my.home-assistant.io/redirect/entities/

Filter for integration "ConnectLife" and status unavailable to identify these entities.

This is documented in https://github.com/oyvindwe/connectlife-ha/tree/main/custom_components/connectlife/data_dictionaries#create-your-own-mapping-file

**Comment by gregrs-uk** [comment]
Thanks @oyvindwe – understood. Sorry to have missed that in the docs.

However, can you please advise why the sensors I've mapped (as `sensor`s rather than `select`s) are hidden (for example the Door sensor in the screenshot above)?

**Comment by oyvindwe** [comment]
@gregrs-uk That is a good question. I wonder if this is something Home Assistant remembers from seeing the sensor initially without a mapping file (as the integration sets all properties as hidden sensors by default).

From https://developers.home-assistant.io/docs/core/entity/#registry-properties :
> Name | Type | Default | Description
> -- | -- | -- | --
> `entity_registry_visible_default` | `bool` | `True` | Indicate if the entity should be hidden or visible when first added to the entity registry.

**Comment by Monacoslo** [comment]
Try to delete and readd integration. It seems to me HA remembers...
