### ISSUE TITLE
Help with device 009-117

### ISSUE THREAD

**Issue by rox97** [oyvindwe/connectlife-ha#124]
<img width="1062" alt="Screenshot 2024-08-26 alle 02 26 07" src="https://github.com/user-attachments/assets/da481fb0-7157-445e-b78f-6eb6e8b6cd03">
I have done everything, but now I have a bunch of sensors. The device type code is 009 and the device feature code is 117

**Comment by oyvindwe** [comment]
Now you need to create a device specific mapping file: https://github.com/oyvindwe/connectlife-ha/tree/main/custom_components/connectlife/data_dictionaries#create-your-own-mapping-file

Either start by using the `dump` tool of `connectife`, or copy on of the other `009-*.yaml` files and start tweaking it.

If you have any questions, just ask here!

**Comment by oyvindwe** [comment]
Fixed by PR #128
