### ISSUE TITLE
009-117 temperature unit

### ISSUE THREAD

**Issue by rox97** [oyvindwe/connectlife-ha#134]
Thank you to @gpillon for his great job, but how can I switch from fahrenheit to celsius?

<img width="681" alt="Screenshot 2024-09-05 alle 00 44 19" src="https://github.com/user-attachments/assets/07312103-4860-47cd-8571-1db0414e7e49">

It's my first time using HASS, forgive me if I ask trivial questions.

**Comment by oyvindwe** [comment]
This is a generic Home Assistant setting: Settings -> General -> Unit System:

<img width="881" alt="image" src="https://github.com/user-attachments/assets/e76c53c2-883f-4649-817a-6ec2bfec8cb4">
