### ISSUE TITLE
009-104 energy usage

### ISSUE THREAD

**Issue by antonioleo89** [oyvindwe/connectlife-ha#144]
Device should 009-104 have property daily_enery_kwh to correctly track the energy usage:
- property: daily_energy_kwh
    sensor:
      read_only: true
      state_class: total_increasing
      device_class: energy
      unit: kWh

**Comment by oyvindwe** [comment]
Indeed - I have added this property to all mapping files where it was missing (this is the only property that I have seen in all JSON dumps so far).

**Comment by oyvindwe** [comment]
Fixed in [version 0.20.1](https://github.com/oyvindwe/connectlife-ha/releases/tag/v0.20.1)
