### ISSUE TITLE
Yesterday worked ok, but now it shows error

### ISSUE THREAD

**Issue by juggalomc** [oyvindwe/connectlife-ha#156]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/connectlife/config_flow.py", line 115, in async_step_select_device
    coordinator = self.hass.data[DOMAIN][self.config_entry.entry_id]
                  ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: '01JBEGM2JFX3H2ACN6GHEV4A53'

**Comment by llllogan** [comment]
I am experiencing something similar.
The integration has been working flawlessly for weeks and then today the connection to the API seems to have broken. I have restarted the integration, re-installed, deleted my CL account and made a new one, cycled my CL password. Nothing seems to work.

<img width="888" alt="image" src="https://github.com/user-attachments/assets/770a0e26-d71a-48c7-a2ea-2c1dd5dfc5d3">

**Comment by oyvindwe** [comment]
This looks like a temporary problem with the API, and insufficient error handling in the config flow.

Did the problem go away again?

**Comment by juggalomc** [comment]
Yes, thanks
