### ISSUE TITLE
Can we add Hisense DH3S802BW3 tumble dryer?

### ISSUE THREAD

**Issue by bastian-nagel** [oyvindwe/connectlife-ha#161]
Can someone help to add this device?
It looks like it´s allmost identical to 030-1wk100028v0w.yaml.
Here is the skeleton file for the DH3S802BW3.
[030-1wk080066v0w.yaml.txt](https://github.com/user-attachments/files/17750989/030-1wk080066v0w.yaml.txt)

**Comment by bastian-nagel** [comment]
I have now added the dryer myself. I have also expanded the translation accordingly.
Since I'm not really familiar with Github, here are the files. Maybe someone else can add it to the repository.
However, one small matter is still open. Current_program_phase only seems to be valid when machine_status is 2 (running). Unfortunately, I still have no idea how to write conditions in yaml...
Maybe someone here can help.
[en.json](https://github.com/user-attachments/files/17775513/en.json)
[030-1wk080066v0w.yaml.txt](https://github.com/user-attachments/files/17775519/030-1wk080066v0w.yaml.txt)
![Trockner](https://github.com/user-attachments/assets/9263f1c1-bcc4-4ba6-a298-f934263b5c00)

**Comment by felix-roc** [comment]
Thanks for the first mappings. I created a pull request.
Do you think it is possible to add remote start? Perhaps setting the program phase?

**Comment by oyvindwe** [comment]
I've been told that remote start requires user pushing a button to enable it on the appliance due to safety regulations.

I can confirm this is the case with my Asko dishwasher, Miele washing machine, _and_ Siemens tumble dryer, so in practice it is usally simpler to just select program on the appliance in any case.

**Comment by bastian-nagel** [comment]
It is definitely possible to start the dryer using the mobile app. So it should also be possible using the API. But first the selector switch on the dryer has to be set to "APP". Which somehow makes the remote start pointless. 🤷‍♂️

**Comment by felix-roc** [comment]
Well, I would like to sync the dryer to solar production or low electricity prices. In that case I would load it in the morning and let HA start it once the sun is out.

**Comment by oyvindwe** [comment]
I think this is possible by enabling remote start on the dryer when it is loaded, but we need to figure out which property to set to start it.

Can you check if you select program on the dryer or in the app, or either, in this case?

You may have to sniff the data to figure out which property to set. I have not done that - it probably requires you to set up a MITM proxy.
