### ISSUE TITLE
Cant login invalid username/password

### ISSUE THREAD

**Issue by NicoVenter** [oyvindwe/connectlife-ha#166]
Hellow team, am i being stupid? 🥇 

1. Droped the folder in the custom_components. 

![image](https://github.com/user-attachments/assets/5575a1cc-569b-4347-9dd1-eea912cf1072)

2 . Added Repo & Installed addon via HACS
![image](https://github.com/user-attachments/assets/d29adfbb-b16a-4133-8149-4dd3583b4363)

3. Unable to see it in integrations ( I did reboot. - between each step).
Not sure if the intention was for it to be displayed in integrations on HomeAssistant. Mine doesn't? Regardless follow link for custom integrations: /config/integrations/integration/connectlife

4. unable to sign-in (yes created a account with them, not using SSO integrated account)
![image](https://github.com/user-attachments/assets/40c28e1c-2b0d-410a-92ea-05f296626504)

- Am I missing something obvious here? 
- No relevant logs in HA.
- Running HAOS

**Comment by oyvindwe** [comment]
You don't need to install the folder manually if you are installing using HACS, so you could have skipped your step 1, but it shouldn't really matter.

If there are authentication issues, try to enable debug logging for the _library_ in addition to the integrationb. In your `configuration.yaml`, set
```
logger:
  default: info
  logs:
    custom_components.connectlife: debug
    connectlife: debug
```

Note: take care if sharing this log - it may contain you password as well as tokens to access the Connectlife API as you.

Also note that at least users in Russia and China seem to be blocked for logging in: https://github.com/oyvindwe/connectlife-ha?tab=readme-ov-file#login

**Comment by NicoVenter** [comment]
Does show wrong username & password. reloaded all again from HACS, tried again and fully functional. seems I was stupid. Thank you.
