### ISSUE TITLE
YAML files for Gorenje dishwasher GS673B60W

### ISSUE THREAD

**Issue by JanHrebec** [oyvindwe/connectlife-ha#173]
I am new to github branches, pull requests etc, so I write it here.
I have made config files for Gorenje dishwasher GS673B60W.
They are attached in this issue (renamed as TXT
[015-dishwasher-50.2f.yaml.txt](https://github.com/user-attachments/files/18117764/015-dishwasher-50.2f.yaml.txt)
[en.json.txt](https://github.com/user-attachments/files/18117765/en.json.txt)
)

**Comment by spattinson** [comment]
Thanks for this. I am about to buy a Hinsense dishwasher with a very similar mode number so hopefully it will be similar. Found this git while checking for an integration for it

**Comment by oyvindwe** [comment]
@JanHrebec Thank you very much!
