### ISSUE TITLE
Dehumidifier missing "current humidity entity"

### ISSUE THREAD

**Issue by trajano** [oyvindwe/connectlife-ha#22]
in 0.5.0 the current humidity entity is missing
![image](https://github.com/oyvindwe/connectlife-ha/assets/110627/180a0181-e0d6-4309-903a-8f0011ef2e11)

**Comment by oyvindwe** [comment]
Yes, this is because it is now a state attribute of humidifier. Whenever the type of a property is changed, the former entity will no longer be created. It will still exist as unavailable in HA until deleted. Another thing that needs to be documented.

**Comment by trajano** [comment]
The problem is now I can't get the current humidity anywhere.

**Comment by trajano** [comment]
![image](https://github.com/oyvindwe/connectlife-ha/assets/110627/f55d4b55-e829-48b1-9b87-bf80f7e1af75)

**Comment by trajano** [comment]
Actually re-opening this unless you claim  that you cannot have both the `current_humidity` device state and the sensor at the same time because at present there's no way I can find to display the current humidity value.

**Comment by oyvindwe** [comment]
It is displayed in the humidifier UI (disregard the actual % value - this is an AC that does not measure humidity which I reconfigured to be a humidifier to create the screenshot):
<img width="551" alt="image" src="https://github.com/oyvindwe/connectlife-ha/assets/5984518/1d59b568-17e8-4210-821a-645a6f1efab0">


Current humidity also shows up in the charts:
<img width="996" alt="image" src="https://github.com/oyvindwe/connectlife-ha/assets/5984518/e8382d7c-07bd-41e7-82bf-45a1cfc3be3f">


If you want to build a dashboard, the "Entity" card can show state attributes:
<img width="1012" alt="image" src="https://github.com/oyvindwe/connectlife-ha/assets/5984518/9dd5d3f9-8f2f-4c98-94a6-beddf08aa599">


Finally, in templates you would do like this (replace the entity id): `{{ state_attr('humidifier.my_dehumidifier', 'current_humidity') }}`

**Comment by trajano** [comment]
I'm actually just trying to get the current humidity value in the "badges" area of the dashboard.  Right now it's not an option.

**Comment by oyvindwe** [comment]
Can you try to create a template sensor of the state attribute from the humidifier entity: https://www.home-assistant.io/integrations/template/ ?

It is not recommended to expose state attributes as sensors as well by the integration to avoid storing the same history on two separate entities.

That said, it is not difficult to support mapping ConnectLife properties to more than one entity, but it goes against a core principle of Home Assistant.

**Comment by trajano** [comment]
Thanks I used `{{ state_attr('humidifier.dehumidifier', 'current_humidity') | float }}` since I want it numeric.  If HA's architecture recommends not to expose it that's fine let's not.  Though I am curious why they made it difficult to get.

**Comment by trajano** [comment]
@oyvindwe I noticed that `current_humidity_changed` trigger does not appear to work.  I am switching it to the template to as a workaround.

**Comment by oyvindwe** [comment]
@trajano That's unfortunate. Did you make a trigger using the template sensor or the state attribute? E.g.:
<img width="1057" alt="image" src="https://github.com/oyvindwe/connectlife-ha/assets/5984518/4c48d1d9-efb2-4f50-9496-998ac0b020c2">

**Comment by trajano** [comment]
Yup that's how I did it.  
![image](https://github.com/oyvindwe/connectlife-ha/assets/110627/f16d6aa2-682a-416f-bfee-1aaad04d3b3d)

**Comment by trajano** [comment]
After 0.7.0 update the template stopped working and I am not getting anything on the badge
![image](https://github.com/oyvindwe/connectlife-ha/assets/110627/3298ba6f-dc67-436c-8f9e-445dee649f35)

**Comment by trajano** [comment]
Actually after the update
![image](https://github.com/oyvindwe/connectlife-ha/assets/110627/fd0ae3ab-d1e6-4877-a723-8bcf162d52cb)

**Comment by oyvindwe** [comment]
Anything in the log?

**Comment by trajano** [comment]
Nothing of note in logbook

**Comment by trajano** [comment]
Deleted and re-added all I see is the fan speed selector

![image](https://github.com/oyvindwe/connectlife-ha/assets/110627/23415e0d-9693-47bf-b110-73b0f612d243)

So likely there are changes on `humidifier` that broke this.

**Comment by trajano** [comment]
Tracking the above problem in a new issue
