### ISSUE TITLE
Add `Drying` action state for the dehumidifier when turned on

### ISSUE THREAD

**Issue by trajano** [oyvindwe/connectlife-ha#23]
There's a action state for `Drying` that should be enabled when the Dehumidifier is running https://developers.home-assistant.io/docs/core/entity/humidifier#action

**Comment by oyvindwe** [comment]
As I understands the action state (similar for climate), is that is should show the actual current action. E.g. in `auto` mode, the dehumidifier would necessarily not always dry the air. I don't see any properties for your device that maps to `action`, but I am happy to add support for `action` as a target in general.

**Comment by oyvindwe** [comment]
Mapping to target `action` for humidifier is added in PR #26
