### ISSUE TITLE
Icon translations should be in icons.json not the data dictionary

### ISSUE THREAD

**Issue by trajano** [oyvindwe/connectlife-ha#25]
Per https://developers.home-assistant.io/blog/2024/01/19/icon-translations?_highlight=icons 

> Each integration can now provide an icons.json file, containing a mapping of states to icons.

**Comment by oyvindwe** [comment]
Interesting. However, as sensor names may be reused across device types in the ConnectLife API, I think we still need to support setting different icons for the same sensor.

We could add some base icons to `icons.json` though. I need to test what happes if icons are set both ins `icons.json` and in code.
