### ISSUE TITLE
Unable to set the fan mode on the dehumidifier

### ISSUE THREAD

**Issue by trajano** [oyvindwe/connectlife-ha#29]
It claims not that it is not implemented.

Note the previous version which did the low level `set state` worked.

![image](https://github.com/oyvindwe/connectlife-ha/assets/110627/1d26a311-6292-45a6-a960-a02625d506fe)

**Comment by oyvindwe** [comment]
That's correct! 🤦 

Fixing right away.

**Comment by oyvindwe** [comment]
Fixed in version 0.7.0
