### ISSUE TITLE
Can not log in

### ISSUE THREAD

**Issue by denissnake** [oyvindwe/connectlife-ha#3]
i cant login - Invalid authentication. just now change the password - nothing.

**Comment by oyvindwe** [comment]
As stated in [README.md](https://github.com/oyvindwe/connectlife-ha/blob/main/README.md):

> Note that probably only European users can log in using this integration. See discussion in https://github.com/bilan/connectlife-api-connector/issues/25

**Comment by hegemmon** [comment]
Reset password - check this in logout your app and login again - I had info I must reset password, after reset - can login
