### ISSUE TITLE
Add a "helper" to allow users to create their own data dictionaries

### ISSUE THREAD

**Issue by trajano** [oyvindwe/connectlife-ha#31]
Not sure how possible this is, but it would be nice to have a "helper" that contains the data dictionary which allows reset to "state in the repo" and provide somehow a way of calling github with the PR or issue generation.

This will allow experimentation locally before sending it up and waiting for integration.

**Comment by oyvindwe** [comment]
I'm using a YAML editor (in IDEA IntelliJ) that validates against the provided [JSON schema](https://github.com/oyvindwe/connectlife-ha/blob/main/custom_components/connectlife/data_dictionaries/properties-schema.json), that is very helpful.

I also expect it to be easier to contribute data dictionaries when there are more samples to look at. I'm trying to complete the code first, and then I plan to add some dictionaries for some of the devices that I have received dumps form here: https://github.com/oyvindwe/connectlife/tree/main/dumps

**Comment by trajano** [comment]
Yeah I do something similar but I'd rather test it before I create a PR.  I think what should happen is I fork the repo and change HACS to point to that one so I can make the changes and push to your repo for an official PR.

**Comment by oyvindwe** [comment]
That is one possibilty.

I am running a dev version of HA where I have symlinked in my local `conncetlife-ha` repo into custom_components:
```
home-assistant % ls -l config/custom_components 
total 0
lrwxr-xr-x  1 omw  staff  53 May  7 08:39 connectlife -> ../../../connectlife-ha/custom_components/connectlife
```

That gives me a very short roundtrip for testing. This HA instance only runs the the integrations I'm actively developing.

**Comment by oyvindwe** [comment]
I have added an option to `connectlife.dump` ([`connectlife`](https://github.com/oyvindwe/connectlife)) that generate data dictionary skeletons. I think that should be useful.

**Comment by oyvindwe** [comment]
Closing as `connectlife.dump` seems to be sufficient (and anything else is fairly comples to make).
