### ISSUE TITLE
Humidifier support

### ISSUE THREAD

**Issue by trajano** [oyvindwe/connectlife-ha#6]
It would be nice to be able to control the fan speed based on the current humidity level so it isn't too noisy when the desired humidity is relatively close and if I am not home.

This is for https://www.costco.ca/.product.1711088.html?&EMID=CA_EN_2024_0608_Treasure_Hunt&correlationId=f3bd9c82-4236-44ca-9a64-acf17de5897f-0

```json
[
  {
    "bindTime": 1719439058604,
    "createTime": 0,
    "deviceFeatureCode": "400",
    "deviceFeatureName": "400\u6709\u81ea\u52a8\u98ce\u65e0\u4e2d\u98ce\u65e0\u529f\u7387",
    "deviceId": "<redacted>",
    "deviceNickName": "Dehumidifier",
    "deviceTypeCode": "007",
    "deviceTypeName": "",
    "offlineState": 1,
    "puid": "<redacted>",
    "role": 1,
    "roomId": 4841165,
    "roomName": "Living Room",
    "seq": 0,
    "statusList": {
      "daily_energy_kwh": 0, // always zero
      "f_e_filterclean": "0", // I think f_e_*  are error flags
      "f_e_pump": "0",
      "f_e_push": "0",
      "f_e_temp": "0", 
      "f_e_tubetemp": "0",
      "f_e_waterfull": "0", // Dehumidifier water bucket full (1==full, 0==not full)
      "f_e_wetsensor": "0",
      "f_humidity": "32", // current humidity in %
      "t_fan_speed": "2", // target fan speed (2 == auto, 1 == high, 0 == low)
      "t_humidity": "40", // target humidity in %
      "t_power": "1", // I think this is if it is on or off
      "t_work_mode": "1" 
        // 1 == manual (which allows setting of target) 
        // 0 == continuous 
        // 2 == auto which basically sets humidity to 50 and auto
    },
    "useTime": 1719439058583,
    "wifiId": "<redacted>"
  }
]
```

**Comment by trajano** [comment]
Based on https://github.com/bilan/connectlife-api-connector the `t_work_mode` is specific to the device.

In #1  his "deviceTypeCode": "009"  so that may be the air conditioner
In my case mine is `"deviceTypeCode": "007"` so that may be the discriminator.

**Comment by oyvindwe** [comment]
Yes, it seems that the status list is specific per `deviceTypeCode`. A bummer that they sometimes reuse field names but with different value domains. I had hope to create a data dictionary only with the field names, but it seems that we need a complete data dictionary per `deviceTypeCode`.

**Comment by oyvindwe** [comment]
Regarding controlling devices in general, see #1

**Comment by trajano** [comment]
Woo I was able to successfully turn on/off the device using `curl` what I needed specifically was the `user-agent` value

```sh
curl \
  -H 'Content-type: application/json' \
  -H 'User-Agent: connectlife-api-connector 3.0' \
  -H 'X-Token: pa...xA' \
  --data '
{
  "puid": "pu000...",
  "properties": { 
    "t_power": "1"
  }
}' https://connectlife.bapi.ovh/appliances
```

**Comment by trajano** [comment]
Used 0.1.0 tried to do the set

> Failed to call service climate.set_humidity. must contain at least one of entity_id, device_id, area_id, floor_id, label_id.. Got {'type': 'execute_script', 'sequence': [{'service': 'climate.set_humidity', 'target': {}, 'data': {'humidity': 30}}], 'id': 89}

Also my dehumidifier is not listed when I try to choose the target.

**Comment by oyvindwe** [comment]
It is a custom entity service. I'll add some documentation to `README.md`. Try this:

Service: ConnectLife: Set value
Target: `sensor.dehumidifier_t_humidity` (copy from entity id of sensor - you may have a different string)

**Comment by trajano** [comment]
Nothing is listed on the targets when I chose `ConnectLife: Set Value`

**Comment by trajano** [comment]
I think you have a `climate` branch, but I am not sure how to switch to that one it would be nice if the setting was done through [climate integration](https://www.home-assistant.io/integrations/climate)

**Comment by oyvindwe** [comment]
> Nothing is listed on the targets when I chose `ConnectLife: Set Value`

Don't you get buttons to select area/source/entity/label? Click on the button to select entity, remove the text and paste in the entity id.

> I think you have a climate branch

That was started prematurely - I realised I first had to be able to actually update properties. As that finally works now, it is possible to continue with it, but I'm currently working on a framework for appliance data dictionaries.

**Comment by trajano** [comment]
For the dictionaries I think a simple YAML structure would be a good enough start.  Don't forget the icons and localization.  Then updates to it can be done via PR.

**Comment by trajano** [comment]
Ok the entity thing works, just quite roundabout to get the value but good enough to start.

**Comment by oyvindwe** [comment]
YAML structure was a good idea. I had started on a CSV structure, but that requires a good editor. I have implemented a framework for data dictionary and an initial data dictionary in PR #9 

I can probably give the climate entity a go next. :)

**Comment by oyvindwe** [comment]
> Don't forget the icons and localization.

Icons was straight forward to support, but localization required some cleanup - all done now (merged but not released).

**Comment by oyvindwe** [comment]
@trajano I have added a data dictionary for your device in [version 0.0.4](https://github.com/oyvindwe/connectlife-ha/releases/tag/v0.4.0). Can you please test and see if i works for you?

Note that I made a select entity of `t_work_mode`, as it does not map to anything in the [climate entity](https://developers.home-assistant.io/docs/core/entity/climate)

**Comment by oyvindwe** [comment]
I was't aware that this should be a separate [entity type](https://developers.home-assistant.io/docs/core/entity/humidifier)

This wiill be next up then!

**Comment by trajano** [comment]
Don't forget mine would be `HumidiferDeviceClass.DEHUMIDIFIER` :D

**Comment by oyvindwe** [comment]
Note that `HumidifierEntity` only has `mode`, so we must map either `t_fan_speed` or `t_work_mode` to a select entity.

Which one do you prefer?

**Comment by oyvindwe** [comment]
Support for `humidifier` implemented in [version 0.5.0](https://github.com/oyvindwe/connectlife-ha/releases/tag/v0.5.0)

Note that it is only partially tested by configuring som properties of an air conditioner to humidifier.

**Comment by trajano** [comment]
Re: [modes](https://developers.home-assistant.io/docs/core/entity/humidifier/#modes) 
>  There are a couple of built-in modes that will offer translations, but you're *also allowed to add custom modes*  if that better represents the device.

That being said for the dehumidifer's `t work mode` value

MODE_NORMAL == 0 continuous
MODE_AUTO	== 2 auto mode on the dehumidifier which does not allow user to set any values
1 == manual

The rest don't apply

Fan-speed doesn't really apply as a "mode" at least not according to their definitions.

Totally it's kinda bad you can't set two entities because if so  the the following values would map to it

MODE_ECO	fan speed low
MODE_BOOST	fan speed high
MODE_COMFORT	fan speed auto

**Comment by oyvindwe** [comment]
I am wondering if `humidifier` (and `climate`) should be added as top level configuration items. Then mappings could be create like e.g. this:
```yaml
humidifier:
  device_class: dehumidifier
  states:
    eco:
      t_eco: 1
      t_fan_speed: 0
      t_work_mode: 2
    boost:
      t_eco: 0
      t_fan_speed: 1
      t_work_mode: 2
    comfort:
      t_eco: 0
      t_fan_speed: 2
      t_work_mode: 2      
```

However, it is a bit problematic if `t_eco` is set to 1 after selecting `boot` or `comfort` in this case, as that combination would not map to a mode, so it would go to `None`.

Thoughts?

**Comment by trajano** [comment]
According to the humidifier docs you should use `MODE_NORMAL` No preset is active, normal operation (that's the more appropriate one rather than `None`

In other words you would have modes being "presets" as it had been noted in https://developers.home-assistant.io/docs/core/entity/humidifier#modes

**Comment by oyvindwe** [comment]
> According to the humidifier docs you should use MODE_NORMAL No preset is active, normal operation (that's the more appropriate one rather than None

This was just an example. My point was if that we start mapping humidifier states to multiple properties, the code need to handle the case where there is no mapping for a combination of underlying states. Combining 3 properties with 2, 3 and 3 different values gives *18* possible states (2*3*3).

Not all of those states may be possible to actually set. In this case, `t_work_mode` `auto` and `t_fan_speed` `low` or `high` cannot be combined (according to your initial observances), but we cannot assume that the mapping will always be complete for all devices.

The question is if this is worth the effort, or if we should stick with 1-1 mapping of properties between devices and Home Assistant entity attributes, at least for now. I would need some help with defining all humidifier states in that case.

**Comment by trajano** [comment]
I prefer keeping it 1-to-1 for now, I can script it for now.

Then having the facility to combine settings into presets (aka modes) later.  Also for those presets we should also add `t_power = on` as well.

Who knows Home Assistant may provide a UI to create shareable custom modes/presets without this having to define it.

**Comment by oyvindwe** [comment]
I also prefer to keep 1-1 mappings for now - it is clean and simple. I will update the documentation to make it clear.

`t_power` is mapped to to `is_on` - I think that is sufficient.

I have also added support for `action`,  but not added any mapping.

**Comment by trajano** [comment]
I'm closing this off for now since the Dehumidifier is there and I'm opening specific bugs
