### ISSUE TITLE
Min and max values are not working in water-heater entity

### ISSUE THREAD

**Issue by bartashevich** [oyvindwe/connectlife-ha#63]
Hi, min and max remain as default 43C-60C, while in configuration it is setup 20C-65C.

![image](https://github.com/user-attachments/assets/f61fc71e-a1f7-4a3f-8a47-000f2d184d89)

**Comment by bartashevich** [comment]
![image](https://github.com/user-attachments/assets/0295ef95-b2ef-4102-bda7-2199e997f0f9)

**Comment by oyvindwe** [comment]
Fixed by PR #65 and included in [version 0.10.1](https://github.com/oyvindwe/connectlife-ha/releases/tag/v0.10.1)

**Comment by bartashevich** [comment]
Thanks. It works now.

**Comment by oyvindwe** [comment]
Thank you for confirming! I'll make a smiliar fix for climate entities..
