### ISSUE TITLE
Where do I go from here?

### ISSUE THREAD

**Issue by aarnaegg** [oyvindwe/connectlife-ha#87]
I have successfully signed into the ConnectLife plug in and get all the sensors for my AC unit (Hisense Smart SACC - AP55023HR1GD). Where do I go from here? I can manually set values using connectlife.set_value. Am I missing something to get on/off switch, temp settings? Maybe I need to provide data dictionaries for this device. I am just seeing it is 006-201.

![Screenshot 2024-07-30 094555](https://github.com/user-attachments/assets/acde76f7-a805-47c3-8921-7746cf525ed8)

**Comment by oyvindwe** [comment]
I have just released [version 0.14.0](https://github.com/oyvindwe/connectlife-ha/releases/tag/v0.14.0) that includes this.

**Comment by aarnaegg** [comment]
Right after I posted this I found the file. Thanks!
