### ISSUE TITLE
https://github.com/oyvindwe/connectlife-ha.git is not a valid add-on repository

### ISSUE THREAD

**Issue by IonasPolitis** [oyvindwe/connectlife-ha#95]
Neither this work: https://github.com/oyvindwe/connectlife-ha/?tab=readme-ov-file, or just this: oyvindwe/connectlife-ha, with the respectable errors: https://github.com/oyvindwe/connectlife-ha is not a valid add-on repository, and: expected a URL for dictionary value @ data['repository']. Got 'oyvindwe/connectlife-ha'

**Comment by oyvindwe** [comment]
This is not an add-on, but an integration you can install using HACS. Please see README.md

**Comment by IonasPolitis** [comment]
Ok, my bad. I got confused. Thanks
